'use client';

import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import BottomAppNavigation from "@/src/components/BottomAppNavigation";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v16-appRouter";
import {Box, ThemeProvider, useTheme} from "@mui/material";
import {theme} from "@/src/styles/theme";
import {MqttProvider} from "@/src/components/mqtt-provider/MqttProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html
            lang="en"
        >
        <body>
        <AppRouterCacheProvider options={{enableCssLayer: true}}>
            <ThemeProvider theme={theme}>
                <Box sx={{
                    display: 'flex',
                    flexDirection: 'column',
                    height: '100dvh',
                }}>
                    <Box sx={{
                        flexGrow: 1,
                        overflowY: 'auto',
                        backgroundColor: 'plat.bg'
                    }}>
                        <MqttProvider>
                            {children}
                        </MqttProvider>
                    </Box>

                    <Box sx={{backgroundColor: 'plat.bg'}}>
                        <BottomAppNavigation/>
                    </Box>
                </Box>
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
